# Generated by Django 4.2.5 on 2023-11-20 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloans',
            name='Due_Date',
            field=models.DateField(default=datetime.datetime(2023, 12, 4, 7, 48, 56, 470761, tzinfo=datetime.timezone.utc)),
        ),
    ]
